### ISSUE TITLE
[5.1.5] ClassNotFoundException on startup MC1.13.1

### ISSUE THREAD

**Issue by steve4744** [Thatsmusic99/HeadsPlus#10]
### Short summary of issue
ClassNotFoundException enabling HeadsPlus at startup
### Server version
` CraftBukkit version git-Spigot-f6a273b-8ab46ff (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)`
### HeadsPlus version
5.1.5
### Detailed description (how you found it, what you were doing at the time)
```[16:24:29 INFO]: [HeadsPlus] Enabling HeadsPlus v5.1.5
[16:24:29 ERROR]: Error occurred while enabling HeadsPlus v5.1.5 (Is it up to date?)
java.lang.NoClassDefFoundError: io/github/thatsmusic99/pg/nms/v1_13_R1/v1_13_R1NMS
        at io.github.thatsmusic99.headsplus.config.HeadsPlusConfigHeads.addUndefinedHeads(HeadsPlusConfigHeads.java:53) ~[?:?]
        at io.github.thatsmusic99.headsplus.config.HeadsPlusConfigHeads.load(HeadsPlusConfigHeads.java:34) ~[?:?]
        at io.github.thatsmusic99.headsplus.config.ConfigSettings.reloadC(ConfigSettings.java:31) ~[?:?]
        at io.github.thatsmusic99.headsplus.config.ConfigSettings.enable(ConfigSettings.java:17) ~[?:?]
        at io.github.thatsmusic99.headsplus.config.HeadsPlusConfigHeads.<init>(HeadsPlusConfigHeads.java:26) ~[?:?]
        at io.github.thatsmusic99.headsplus.HeadsPlus.createInstances(HeadsPlus.java:358) ~[?:?]
        at io.github.thatsmusic99.headsplus.HeadsPlus.onEnable(HeadsPlus.java:100) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:431) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:345) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: io.github.thatsmusic99.pg.nms.v1_13_R1.v1_13_R1NMS
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        ... 18 more`
### Expected behaviour
not that
### Actual behaviour
as above
### Steps to reproduce
restart server
### Any last notes?

**Comment by Thatsmusic99** [comment]
Does this come up more than once? If it's one off then it should be okay, if not, I don't know what's going on.

**Comment by steve4744** [comment]
Yeah, each time the server starts up.

**Comment by Thatsmusic99** [comment]
Will double check it. I'm pretty sure I didn't have that issue when starting the server up...

**Comment by Thatsmusic99** [comment]
Oh my God I just realised what I did wrong. Will fix in the latest version.

**Comment by Thatsmusic99** [comment]
Fixed as of now.

**Comment by steve4744** [comment]
Yeah - that's working now. Thanks
