### ISSUE TITLE
error[BUG]

### ISSUE THREAD

**Issue by Yamiru** [Thatsmusic99/HeadsPlus#20]
## FIRST-HAND CHECK - ARE YOU USING THE LATEST VERSION/SNAPSHOT OF HEADSPLUS? 
paperspigot 1.15.2 #143
headsplus 6.9.4

### Description of the bug
error console
1. after player connect to server
2. some errors

### To Reproduce
- only system error

### Expected behavior
no errors

### Screenshots
console bug

### Has a debug report been generated? 
[HeadsPlus] Task #213413 for HeadsPlus v6.9.4 generated an exception
23.03 16:50:43 [Server] INFO java.lang.NullPointerException: null
[15:55:05] [Server thread/WARN]: [HeadsPlus] Task #213413 for HeadsPlus v6.9.4 generated an exception
java.lang.NullPointerException: null
	at io.github.thatsmusic99.headsplus.api.HPPlayer.clearMask(HPPlayer.java:110) ~[?:?]
	at io.github.thatsmusic99.headsplus.listeners.MaskEvent$1.run(MaskEvent.java:47) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-143]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
	at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:518) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:42) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.dropItem(CraftWorld.java:696) ~[patched_1.15.2.jar:git-Paper-143]
	at io.github.thatsmusic99.headsplus.listeners.DeathEvents.dropHead(DeathEvents.java:414) ~[?:?]
	at io.github.thatsmusic99.headsplus.listeners.DeathEvents.onEntityDeath(DeathEvents.java:184) ~[?:?]

### Required information
- Server version: paperspigot 1.15.2 #143
- HeadsPlus version:6.9.4
- no MySQL
- Server type paperspigot
- Uses Vault: yes

## Additional information
-

**Comment by Thatsmusic99** [comment]
Does this fix any of the errors in question? https://github.com/Thatsmusic99/HeadsPlus/releases/tag/v6.9.5-SNAPSHOT-1

**Comment by Yamiru** [comment]
thank you
