### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by broken1arrow** [Thatsmusic99/HeadsPlus#22]
## FIRST-HAND CHECK - ARE YOU USING THE LATEST VERSION/SNAPSHOT OF HEADSPLUS? 
6.10.5 snapshot-1

### Description of the bug
I´m has put in around 150 heads (was 195 heads in one menu).
If i´m not has done any own errors (it work first, but now is get this error after reload). 

### To Reproduce
1. ... I´m not certain, I´m not so good on error codes (and google is often get little or no result). 
2. ...
3. ...

### Have you been able to reproduce the bug more than once?
No, not mre and try to reload plugin
and now I get (if i use /heads):
21.05 22:38:05 [Server] INFO broken_arrow1 issued server command: /heads
21.05 22:38:05 [Server] WARN java.lang.ArrayIndexOutOfBoundsException 
### Screenshots
[22:04:17] [Server thread/INFO]: broken_arrow1 issued server command: /headsplus Reload
[22:04:17] [Server thread/INFO]: broken_arrow1 Är tillbaka från AFK
[22:04:21] [Server thread/INFO]: broken_arrow1 issued server command: /heads
[22:04:21] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: 1
[22:04:21] [Server thread/WARN]: 	at io.github.thatsmusic99.headsplus.config.customheads.HeadsPlusConfigCustomHeads.getSkull(HeadsPlusConfigCustomHeads.java:180)
[22:04:21] [Server thread/WARN]: 	at io.github.thatsmusic99.headsplus.inventories.list.HeadsMenu.transformContents(HeadsMenu.java:54)
[22:04:21] [Server thread/WARN]: 	at io.github.thatsmusic99.headsplus.inventories.BaseInventory.<init>(BaseInventory.java:68)
[22:04:21] [Server thread/WARN]: 	at io.github.thatsmusic99.headsplus.inventories.list.HeadsMenu.<init>(HeadsMenu.java:20)
[22:04:21] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[22:04:21] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[22:04:21] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[22:04:21] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[22:04:21] [Server thread/WARN]: 	at io.github.thatsmusic99.headsplus.inventories.InventoryManager.open(InventoryManager.java:113)
[22:04:21] [Server thread/WARN]: 	at io.github.thatsmusic99.headsplus.commands.Heads.onCommand(Heads.java:35)
[22:04:21] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[22:04:21] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[22:04:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761)
[22:04:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1860)
[22:04:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1668)
[22:04:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[22:04:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[22:04:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[22:04:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[22:04:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[22:04:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[22:04:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[22:04:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1097)
[22:04:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1090)
[22:04:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[22:04:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1051)
[22:04:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:966)
[22:04:21] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

### Has a debug report been generated? 
If you have a debug report, go to plugin/HeadsPlus/debug, copy your report onto pastebin or hastebin, and paste it here, but also skip to the bottom question (additional information). If you don't, fill in the information below.

### Required information
- Server version: 294 
- HeadsPlus version: 6.10.5 snapshot-1
- Whether or not the plugin uses MySQL
- Server type (e.g Spigot, Paper): Paper
- Uses Vault: yes
- Any other pieces of information that may be required.
CMI
## Additional information
Add any other information/notes you'd like to add at the bottom
Heads file
[customheads.zip](https://github.com/Thatsmusic99/HeadsPlus/files/4665181/customheads.zip)

**Comment by Thatsmusic99** [comment]
Will attempt to reproduce but do take note that v6.10.5 has a full release now on SpigotMC; only issue is that it has not fixed any errors of the such.

**Comment by Thatsmusic99** [comment]
This is a configuration fault - on line 46, you've provided no head ID for the plugin to pick a texture from. An example of this can be HP#wood_a or HP#lizard. Either way, I'll see if I can make it so that the cause of the error is clear.

**Comment by broken1arrow** [comment]
> 
> 
> This is a configuration fault - on line 46, you've provided no head ID for the plugin to pick a texture from. An example of this can be HP#wood_a or HP#lizard. Either way, I'll see if I can make it so that the cause of the error is clear.

Yes fix better error msg, most be a mistake from my side (i´m most delete this of mistake).

**Comment by Thatsmusic99** [comment]
Error message added as of v6.10.8.
