### ISSUE TITLE
MySQL Error: Column 'ZOMBIE_VILLAGER' specified twice

### ISSUE THREAD

**Issue by jascotty2** [Thatsmusic99/HeadsPlus#29]
Fresh install of plugin on a new server, version 1.13.2, enabled MySQL database and craft-heads in inventory, then on crafting a squid head with a skeleton skull and an ink sack:

```
[12:41:45 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Column 'ZOMBIE_VILLAGER' specified twice
[12:41:45 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[12:41:45 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[12:41:45 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[12:41:45 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[12:41:45 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[12:41:45 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:408)
[12:41:45 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[12:41:45 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
[12:41:45 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
[12:41:45 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
[12:41:45 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
[12:41:45 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491)
[12:41:45 WARN]:        at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1552)
[12:41:45 WARN]:        at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2607)
[12:41:45 WARN]:        at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1480)
[12:41:45 WARN]:        at io.github.thatsmusic99.headsplus.util.MySQLAPI.addNewPlayerValue(MySQLAPI.java:62)
[12:41:45 WARN]:        at io.github.thatsmusic99.headsplus.util.MySQLAPI.addOntoValue(MySQLAPI.java:189)
[12:41:45 WARN]:        at io.github.thatsmusic99.headsplus.listeners.LBEvents.onHeadCraft(LBEvents.java:89)
[12:41:45 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor368.execute(Unknown Source)
[12:41:45 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[12:41:45 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[12:41:45 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
[12:41:45 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520)
[12:41:45 WARN]:        at io.github.thatsmusic99.headsplus.crafting.RecipePerms.fireEvent(RecipePerms.java:116)
[12:41:45 WARN]:        at io.github.thatsmusic99.headsplus.crafting.RecipePerms.onCraft(RecipePerms.java:44)
[12:41:45 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor360.execute(Unknown Source)
[12:41:45 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[12:41:45 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[12:41:45 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
[12:41:45 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520)
[12:41:45 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2287)
[12:41:45 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33)
[12:41:45 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10)
[12:41:45 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
[12:41:45 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[12:41:45 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[12:41:45 WARN]:        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
[12:41:45 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018)
[12:41:45 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[12:41:45 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[12:41:45 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
[12:41:45 WARN]:        at java.lang.Thread.run(Unknown Source)
[12:41:45 ERROR]: [HeadsPlus] HeadsPlus has failed to execute this task. An error report has been made in /plugins/HeadsPlus/debug
[12:41:45 ERROR]: [HeadsPlus] Report name: 05.13.2019 12_41_45-REPORT-0.json
[12:41:45 ERROR]: [HeadsPlus] Please submit this report to the developer at one of the following links:
[12:41:45 ERROR]: [HeadsPlus] https://github.com/Thatsmusic99/HeadsPlus/issues
[12:41:45 ERROR]: [HeadsPlus] https://discord.gg/nbT7wC2
[12:41:45 ERROR]: [HeadsPlus] https://www.spigotmc.org/threads/headsplus-1-8-x-1-12-x.237088/
```

More Information: 
```
    "Server version": "git-Paper-614 (MC: 1.13.2)",
    "HeadsPlus version": "6.1.2",
    "Plugin values": {
      "MySQL is enabled": true,
      "Masks enabled": true,
      "Uses leaderboards": true,
      "Levels enabled": true,
      "Allows looting enchantment": true,
      "Uses heads selector": true,
      "Cached players": 1,
      "Total levels": 31,
      "Stops placement of sellable heads": false,
      "Droppable heads enabled": true,
      "Player death messages": true,
      "Total challenges": 38
    },
    "NMS version": "v1_13_R2_NMS",
    "Date": "05/13/2019 12:41:45",
    "Has Vault hooked": true
```

I tried to load the code to fix it myself, but gave up after an hour.. getting that pom to work in maven is a nightmare, lol.

**Comment by Thatsmusic99** [comment]
Will do a quick check to make sure this doesn't happen on 6.1.3-SNAPSHOT-1.

And yes, I'm aware the pom is a nightmare. I probably have to redo this whole repo at some point..

**Comment by jascotty2** [comment]
Retested with the version on the github (I'm now annoyed that I only now found that page, heh) - that version works
https://github.com/Thatsmusic99/HeadsPlus/releases/tag/v6.1.3-SNAPSHOT-1
