### ISSUE TITLE
Database did not update for new fields in 1.14

### ISSUE THREAD

**Issue by jascotty2** [Thatsmusic99/HeadsPlus#30]
When running the plugin in 1.14.1 after upgrading a 1.13 server, killing entities throws this error:
```
[12:10:41 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'FOX' in 'field list'
[12:10:41 WARN]:        at sun.reflect.GeneratedConstructorAccessor70.newInstance(Unknown Source)
[12:10:41 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[12:10:41 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[12:10:41 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[12:10:41 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:408)
[12:10:41 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[12:10:41 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
[12:10:41 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
[12:10:41 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
[12:10:41 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
[12:10:41 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491)
[12:10:41 WARN]:        at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1552)
[12:10:41 WARN]:        at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2607)
[12:10:41 WARN]:        at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1480)
[12:10:41 WARN]:        at io.github.thatsmusic99.headsplus.util.MySQLAPI.addNewPlayerValue(MySQLAPI.java:62)
[12:10:41 WARN]:        at io.github.thatsmusic99.headsplus.util.MySQLAPI.addOntoValue(MySQLAPI.java:146)
[12:10:41 WARN]:        at io.github.thatsmusic99.headsplus.listeners.LBEvents.onPHeadDrop(LBEvents.java:49)
[12:10:41 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2243.execute(Unknown Source)
[12:10:41 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[12:10:41 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[12:10:41 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[12:10:41 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:534)
[12:10:41 WARN]:        at io.github.thatsmusic99.headsplus.listeners.DeathEvents.onPlayerDeath(DeathEvents.java:145)
[12:10:41 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2237.execute(Unknown Source)
[12:10:41 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[12:10:41 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[12:10:41 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[12:10:41 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:534)
[12:10:41 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:752)
[12:10:41 WARN]:        at net.minecraft.server.v1_14_R1.EntityPlayer.die(EntityPlayer.java:572)
[12:10:41 WARN]:        at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity(EntityLiving.java:1192)
[12:10:41 WARN]:        at net.minecraft.server.v1_14_R1.EntityHuman.damageEntity(EntityHuman.java:770)
[12:10:41 WARN]:        at net.minecraft.server.v1_14_R1.EntityPlayer.damageEntity(EntityPlayer.java:743)
[12:10:41 WARN]:        at net.minecraft.server.v1_14_R1.EntityHuman.attack(EntityHuman.java:1031)
[12:10:41 WARN]:        at net.minecraft.server.v1_14_R1.EntityPlayer.attack(EntityPlayer.java:1671)
[12:10:41 WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2057)
[12:10:41 WARN]:        at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:51)
[12:10:41 WARN]:        at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6)
[12:10:41 WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18)
[12:10:41 WARN]:        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[12:10:41 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127)
[12:10:41 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[12:10:41 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105)
[12:10:41 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:995)
[12:10:41 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:988)
[12:10:41 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115)
[12:10:41 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:972)
[12:10:41 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:906)
[12:10:41 WARN]:        at java.lang.Thread.run(Unknown Source)
[12:10:41 ERROR]: [HeadsPlus] HeadsPlus has failed to execute this task. An error report has been made in /plugins/HeadsPlus/debug
[12:10:41 ERROR]: [HeadsPlus] Report name: 05.20.2019 12_10_41-REPORT-0.json
[12:10:41 ERROR]: [HeadsPlus] Please submit this report to the developer at one of the following links:
[12:10:41 ERROR]: [HeadsPlus] https://github.com/Thatsmusic99/HeadsPlus/issues
[12:10:41 ERROR]: [HeadsPlus] https://discord.gg/nbT7wC2
[12:10:41 ERROR]: [HeadsPlus] https://www.spigotmc.org/threads/headsplus-1-8-x-1-12-x.237088/
```

Dropping the tables resolves the issue, so it just needs to check and add the columns

**Comment by Thatsmusic99** [comment]
What was the HP version you used at the time when updating? v6.1.3 fixed some issues with MySQL. 

(Just as an end note too. The reports that the plugin generates are recommended to be sent more than just the error, because there are some details I need to be aware of)

**Comment by jascotty2** [comment]
Was using the most recent version (I checked this time, lol)
```
    "Server version": "git-Paper-32 (MC: 1.14.1)",
    "HeadsPlus version": "6.2-SNAPSHOT-1",
    "Plugin values": {
      "MySQL is enabled": true,
      "Masks enabled": true,
      "Uses leaderboards": true,
      "Levels enabled": true,
      "Allows looting enchantment": true,
      "Uses heads selector": true,
      "Cached players": 1,
      "Total levels": 31,
      "Stops placement of sellable heads": false,
      "Droppable heads enabled": true,
      "Player death messages": true,
      "Total challenges": 38
    },
    "NMS version": "v1_14_R1_NMS",
```

**Comment by Thatsmusic99** [comment]
Alright, thank you xD will double check to make sure new columns are added.

**Comment by Thatsmusic99** [comment]
Fixed in latest snapshot: https://github.com/Thatsmusic99/HeadsPlus/releases/tag/v6.2-SNAPSHOT-2

**Comment by jascotty2** [comment]
Thanks for the quick turnaround!
Tested it, and it works! :D
